rust-mobile/xbuild

xcli/src/cargo/mod.rs
This causes host headers to be mixed with Android headers, resulting in duplicate includes.  Setting the sysroot does not have this problem, as the compiler is likely configured to not even consider host headers at all.
=> xcli/cargo: Use sysroot for Android NDK instead of piecing together include paths

apk/src/manifest.rs
When declaring an Android manifest the user should not suddenly be
forced to define the `sdk` element with versions, as they're not
required to specify this when omitting the manifest entirely either.
This matches what `android-ndk-rs` is doing from the get-go.
---
@dvc94ch Not entirely sure about this one since `android-ndk-rs` has it since the serde refactor so it isn't something new, perhaps you removed it for good reason?
=> apk/manifest: Add missing `serde(default)` to `sdk` member

.github/workflows/ci.yml
These secrets are not available in forks nor PRs from forks, leading to incessant CI failures for external contributors.
=> ci: Only run jobs requiring secrets on the `cloudpeers` main repo

.github/workflows/ci.yml, mvn/src/lib.rs, xbuild/src/cargo/mod.rs, xbuild/src/command/build.rs, xbuild/src/command/doctor.rs, xbuild/src/lib.rs, xcommon/Cargo.toml, xcommon/src/lib.rs, xcommon/src/llvm.rs
Fixes #47
Dynamic libraries that a Rust library links against while not being present on the target platform (`libc++_shared.so` and other custom libraries) need to be bundled in the APK specifically.  This approach is adopted frm `android-ndk-rs` while switching from `readelf` to `llvm-readelf`.
=> Use `llvm-readelf` to detect and bundle needed dynamic libs for Android

xbuild/src/devices/adb.rs
`ACTION_MAIN` is what `cargo-apk` uses and what both it and `xbuild` create the Activity `intent-filter` with in `AndroidManifest.xml`.  With `android.intent.action.RUN`, on at least a recently updated phone to Android 13, this `am start` call otherwise fails with:
Starting: Intent { act=android.intent.action.RUN cmp=nl.my_app/android.app.NativeActivity }
Error type 3
Error: Activity class {nl.my_app/android.app.NativeActivity} does not exist.
=> devices/adb: Launch app with `ACTION_MAIN`, not `ACTION_RUN`

xbuild/src/cargo/mod.rs, xbuild/src/lib.rs
In order to build projects with features in `xbuild`, it has to accept these on the command line and pass them on to the underlying `cargo` invocation.
=> xbuild/cargo: Pass features with `--features` or `-F` to `cargo`

xbuild/src/cargo/config.rs, xbuild/src/cargo/manifest.rs, xbuild/src/cargo/mod.rs, xbuild/src/cargo/utils.rs, xbuild/src/gradle/mod.rs, xbuild/src/lib.rs
Import cargo workspace changes from cargo-subcommand in preparation for workspace inheritance.
This effectively synchronizes us with:
https://github.com/dvc94ch/cargo-subcommand/pull/23
https://github.com/dvc94ch/cargo-subcommand/pull/24
https://github.com/dvc94ch/cargo-subcommand/pull/25
(and a tiny initial bit of https://github.com/dvc94ch/cargo-subcommand/pull/12)
@dvc94ch the changes from https://github.com/dvc94ch/cargo-subcommand/pull/25 are still WIP, would you mind checking them out with me (see TODOs) and deciding where to go next?
=> xbuild/cargo: Linearize workspace detection

xbuild/src/cargo/manifest.rs, xbuild/src/cargo/mod.rs, xbuild/src/config.rs, xbuild/src/lib.rs
Depends on #83
Starting with [Rust 1.64] common `[package]` parameters (and dependencies) can now be specified in the workspace root manifest by setting `<field>.workspace=true` in a `[package]` and specifying its value in the workspace root manifest under [`[workspace.package]`](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacepackage-table).
Since `xbuild` reads the `version` and `description` field from `[package]` it has to support this new format and pull the values from the root manifest instead, in order to support projects utilizing this new format.
This is currently implemented ad-hoc for the version and description field, but could be done in a cleaner way if/when more fields are needed.
[Rust 1.64]: …
=> Inherit package configuration (`version` and `description`) from workspace root

README.md, xbuild/src/cargo/manifest.rs, xbuild/src/cargo/mod.rs, xbuild/src/cargo/utils.rs, xbuild/src/command/build.rs
The previous implementation had one fatal flaw: having a non-workspace `Cargo.toml` in a subdirectory, with a `[workspace]` defined some directories higher is invalid when that `[workspace]` doesn't include the given `Cargo.toml` subdirectory/package.  `cargo` rejects this with a `current package believes it's in a workspace when it's not`, and we should do the same instead of having an `unwrap_or_else` that falls back to using the workspace root `Cargo.toml` as a package (especially if it might not contain a `[package]` at all).
This would for example fail when running `x new template` in the repo directory, `cd`'ing into it and invoking `x build`.  Instead of complaining about `template/Cargo.toml` not being part of the workspace, it detects the workspace and falls back to building the …
=> Reject subdirectory manifests that are not members of the workspace

apk/src/compiler/xml.rs, xbuild/src/command/mod.rs, xbuild/src/download.rs, xbuild/src/lib.rs, xcommon/src/lib.rs
`clippy::unused_format_specs` pointed out that we were actually concatenating `device.arch()` to `device.details()` because alignment args don't apply to nested `format_args!` invocations.
For example, see how the last two columns are concatenated instead of aligned (alignment shortened for brevity elsewhere):
host            Linux   linux x64Arch Linux 6.0.12-arch1-1
adb:mydeviceid  b0s     android arm64Android 13 (API 33)
=> Fix Rust 1.66 clippy lints including `clippy::unused_format_specs`

Cargo.toml, appbundle/Cargo.toml, xbuild/template/Cargo.toml
`0.20.1-pre` appears to be unpublished, making `xbuild` not compile anymore unless switching to the released `0.21.0` version, allowing us to drop the git patch too.
=> appbundle: Switch to released `apple-codesign 0.21.0`

xbuild/template/Cargo.toml, xbuild/template/lib.rs
Use the re-exported `wry` from `dioxus-desktop` to avoid possible conflict in case of deps upgrade.
=> chore: remove wry dependency from template

xbuild/src/devices/adb.rs
When capturing process output both `stdout` and `stderr` are collected by Rust instead of forwarded to the console.  When such a command has a non-zero exit code, at the very least emit `stderr` within the `anyhow` error message so that users know what's up: for me it's typically:
Error: adb getprop exited with code Some(1)
that now results in a more sensible:
Error: adb getprop exited with code Some(1): adb: device '<id>' not found
=> adb: Print `stderr` on negative status when capturing output

apk/src/manifest.rs
This currently only has 3 predefined values, and will be converted to an integer (enum) by the resource compiler:
https://developer.android.com/reference/android/R.attr#colorMode
https://developer.android.com/guide/topics/manifest/activity-element#colormode
=> apk/manifest: Add `android:colorMode` attribute to `Activity`

xbuild/src/devices/adb.rs
Besides disabling stdout/stderr separation (effectively merging them together), `-x` ignores remote exit codes meaning failures in shell commands don't get propagated and don't fail the invocation.
=> adb: Don't ignore remote exit codes

xbuild/src/devices/adb.rs
Sometimes the app hasn't started yet, and `xbuild` fails with:
Error: failed to get pid:
because `pidof` could not find any process with that name, and exits with a non-zero error code (and stderr is left empty).  Simply passing `-W` to make `am start` block a little while longer until the app is actually running seems to resolve this issue in the common case.
=> adb: Pass `-W` (wait for app start) to `am start` before getting `pidof`

xbuild/src/lib.rs
It should be perfectly sensible to switch between `aab` and `apk` formats while still using `--device` to build for and install the resulting package on a specific connected device.
Additionally we could look at Clap's argument groups to properly convey mutual-exclusivity between `--store`, `--device` and `--arch`+`--platform`.  It is of course true that this `--format` argument has _some_ dependencies/limitations on all those flags too (i.e. when `--device` specifies Android, `--format` must be `apk` or `aab`), but that might be too complicated to represent in Clap.
=> Allow setting `--format` when building for / running on a `--device`

xbuild/src/command/build.rs, xbuild/src/config.rs, xcommon/src/llvm.rs
Certain apps and crates `dlopen` libraries at runtime (which are not listed in the shared library table by design, hence not found by `llvm-readobj`).  Facilitate this by allowing the user to specify a list of folders that need to be scanned for libraries to include in the final package at while building.  This folder structure includes the platform ABI to select the desired shared libraries.
=> Append `runtime_libs` specified in manifest to APK

appimage/src/lib.rs, xcommon/src/lib.rs
The use of this type is behind a `cfg(unix)`, resulting in unused imports on Windows.
Perhaps we should adjust the CI to obstruct merging on clippy lints on any platform?
=> Fix unused `Permissions` import lint warning on Windows

xbuild/src/config.rs, xbuild/src/devices/adb.rs, xbuild/src/devices/mod.rs
Just like a similar PR for `cargo-apk` we'd like to set up some port forwarding to/from a debug phone automatically while using `x run`.  This allows configuring a mapping of ports under the `debug:` section of `android:` in `manifest.yaml`.
=> Configure `adb forward` and `adb reverse` for `x run`

apk/src/lib.rs, msix/src/lib.rs, xbuild/src/command/build.rs, xbuild/src/config.rs, xcommon/src/lib.rs
Fixes #82 
Android apps might want to ship with extra files - assets - to complement the native build.  These could be single files or folders that are included recursively.  the `file_name()` of the given path is added directly to the `assets/` directory, and any directory structure beyond that point is maintained.
Assets are specified in the following way in `manifest.yaml`:
```yaml
android:
assets:
- some/path
- { path: some/path } # Same as above
- { path: some/path, optional: true } # Do not error if this  path doesn't exist
- { path: some/path, alignment: 4096 } # Page-aligned for optimal use with AASSET_MODE_BUFFER and AAsset_getBuffer
- { path: some/path, alignment: unaligned }
- { path: some/path, alignment: compressed }
```
=> apk: Embed configurable assets in `asset/` directory

xbuild/src/cargo/config.rs, xbuild/src/cargo/mod.rs, xbuild/src/lib.rs, xbuild/src/main.rs
Environment variables can be set and optionally override the process environment through `.cargo/config.toml`'s `[env]` section: https://doc.rust-lang.org/cargo/reference/config.html#env
These config variables have specific precedence rules with regards to overriding the environment set in the process, and can optionally represent paths relative to the parent of the containing `.cargo/` folder.
Besides exposing variables to all other processes called by `xbuild`, this also allows `xbuild` itself to be driven by variables set in `.cargo/config.toml`, such as `$ANDROID_HOME` needed for #116.
https://github.com/rust-mobile/cargo-subcommand/pull/12
https://github.com/rust-mobile/cargo-subcommand/pull/16
=> Propagate `.cargo/config.toml` `[env]` settings to the process environment

xbuild/src/command/doctor.rs
Excerpt from https://github.com/rust-mobile/xbuild/pull/116#discussion_r1297423973
On Windows at least `adb` prints it version string with carriage return; leaving the `\r` in there (by only splitting on `\n`) and not trimming the string causes us to print its version with a `\r` at the end, clearing the whole line (i.e. it would print `adb     1.0.41\r` followed by the path, and then only the path remains on this line).
Rust's `.lines()` implementation already takes care of this by splitting (inclusively) on `\n` and trimming off that `\n` and _optionally also a `\r`_ in the iterator before returning it to us.
=> doctor: Split version str with `.lines()` to account for Windows' `\r\n`

xbuild/src/devices/adb.rs
Having never really understood how Android Studio does it, I just stumbled upon this very new [stackoverflow answer] that has a rather beatiful solution to the current problems with `pidof`, without drawbacks.  Pidof has always been flaky as it relies on the app to be running, which may either take some time or never happen if the app crashed before `pidof` is first run.  This results in silly workarounds such as loops that induce extra delay and need to have an upper bound. And this `pid` changes every time the app is restarted, making it a tedious process that also doesn't react to manual app restarts on the device.  Retrieving the `uid` via `pm list packages -U` on the other hand, and passing that to `logcat --uid` has the following advantages:
- Always available immediately after the …
=> adb: Use `uid` to limit `logcat` to the current application

xbuild/Cargo.toml
This allows the release executable to be a single static binary on Linux platforms. Closes #132
=> Use rustls instead of OpenSSL TLS

xbuild/src/devices/adb.rs
This effectively reverts commit bf478adbae4e3ece3e5c3f3de85404c88a127593 (#118) without touching code improvements elsewhere.  `-W` makes app start-up significantly slower, sometimes leaving the user wait up to 10 seconds even if the app has already started and crashed without showing any `logcat` output.  It has now become unnecessary since using the app `uid` as filter in #131, which is always available as long as the app is installed and doesn't rely on a running (**before** having crashed!) executable for a process id.
=> adb: Drop `-W` (wait for app) from `am start` for faster `--uid` filter

xbuild/src/download.rs
Excerpt from https://github.com/rust-mobile/xbuild/pull/127 expanded to all platforms: we already have `rustup_triple()` for all target architectures available, instead of hardcoding one specific architecture per platform.
=> download: Generalize `rustup_target()` install in `prefetch()`

xbuild/src/devices/adb.rs
The positional `FILTER` argument to `pm list package` works as a substring match: if you have a package named `foo.bar.baz` and `foo.bar.baz_debug` for example, and try to run `foo.bar.baz`, both packages will be returned, the `_debug`-suffixed one likely first, and the wrong UID ends up being used as `logcat` filter.
To counter that we could use the very slow and extremely verbose (thousands of lines) `pm dump PACKAGE`, _or_ look for the right explicit text match in the line-based `package:foo.bar.baz uid:1234` output from `pm list package`: the latter approach is chosen here.
=> adb: Explicitly match package name in `pm list package` output

xbuild/src/cargo/mod.rs
Installs rustup targets for all targeted android architectures, not just Arch::Arm64.
Changes clang link phase --target parameter to match the build target triple.
resolves #126
=> Support the x86_64-linux-android build target.

xbuild/src/devices/adb.rs
When running the `lldb` command, `lldb-server` wouldn't be copied to the device, no matter if this was present on the `xbuild` host desktop or not. This would result in `lldb` saying it's not able to connect through the target port, but the warning that the copy failed because the executable wasn't present on the source desktop path was the real issue.
Some arguments were flipped quite some time ago, which caused it to always use the wrong path. Also, by default it would not allow for execution so added a `chmod 777` to complete. Running this with on a clean device now correctly launches `lldb` from start to finish. Note that it is strange that the respective `push` commands don't indicate a failure, despite the source file (i.e. the `lldb-server` executable) not being present. After …
=> Fix `lldb-server` not copied to target device

xbuild/src/cargo/mod.rs
`xbuild` uses the headers from `xwin` to support cross-compiling, but doesn't fully replicate the other setup steps that it proposes to provide a valid and working cross-compilation setup to MSVC.  We need to make the following changes:
- `clang-cl` must be used (a `clang` driver with `cl.exe` interface), as all native projects will call `CC`/`CXX` with flags that are only compatible with `cl.exe`;
- `-I` does not seem to set up the system headers correctly, for this `-imsvc` should be used;
- Remove `-Clink-arg=-fuse-ld=lld-link` because we have already selected a linker for Rust with the `LINKER` env var (see warning below). We might instead want to set it in `C(XX)FLAGS` so that when a native crate uses `CC`/`CXX` to link libraries, it can use `lld-link` instead of (probably, like …
=> cargo: Use the right LLVM tools and arguments for MSVC cross-compilation

.github/workflows/ci.yml, apk/src/compiler/table.rs, apk/src/res.rs, mvn/src/package.rs, mvn/src/pom.rs, xbuild/src/download.rs, xcommon/src/lib.rs
Clippy is once again detecting more noise and simplifications in codebases :tada:
=> Fix new Rust 1.83 clippy lints

xbuild/src/lib.rs
Fixes #194, @SolidTux please test this.
Passing `--format exe` would fail, complaining that the "arch" `exe` is not supported.  Copy-paste mistakes from "arch" to "format" aside, the `"exe"` string wasn't in the match arm (missed in da16695c18020216a6bed3993c1a77875f94ac57).
Realistically, as we are already utilizing `clap`, we should remove all this error-prone (proven by this example) open-coding of broken parsers and utilize their derives to automatically generate conversion functions.
This should at the same time assist us in generating help files, as the hardcoded documentation for `--format` currently states that `exe` is a supported value.
=> Fix missing `"exe"` variant and copy-paste mistakes in `Format`

xbuild/src/lib.rs
Fixes #194, closes #196, CC @SolidTux for testing.
We've seen that `impl FromStr for Format` missed the `"exe"` match arm in parsing (#194) despite being listed in the allowed values in our top-level documentation and help text.
Instead of fixing this mistake, remove open-coded `FromStr` entirely and rely on `clap`'s excellent `ValueEnum` derive.  This not only generates a **complete** parser (with the option for attributes to change variant names) but also automates generation of a list of possible values, getting rid of any ambiguity/duplication/copy-paste errors we might have or create in the future:
❯ cargo r -- build -h
...
Usage: x build [OPTIONS]
Options:
...
--platform <PLATFORM>
Build artifacts for target platform [possible values: android, ios, linux, macos, windows]
--arch …
=> Replace broken open-coding of `FromStr` with `derive(clap::ValueEnum)`

xbuild/src/command/build.rs, xcommon/src/lib.rs
Whenever a _user configurable_ path is not found, this currently prints a useless "File not found" without any additional context _which_ path was attempted nor where it was configured.  By explaining what we're doing in the error messages, users are more likely to know what and where to correct.
=> Add missing "path context" for more IO failures

apk/src/lib.rs, apk/src/utils.rs, xbuild/src/command/build.rs, xbuild/src/gradle/mod.rs
The `gradle` build was only including the target library from `cargo`, but not any (in)direct dependencies like `libc++_shared.so`.
Move the logic where we recursively scan all libraries, and pass the result to the `gradle` builder in addition to the existing `apk` builder.
---
Code is a bit nasty so I might want to improve this before we land it, but at least it works.
=> apk: Include recursive libraries via `gradle` as well

.github/workflows/sdk.yml
[Rust 1.68 is now targeting NDK r25] instead of r17 and no longer tries to forcibly link against `libgcc.a`, which was removed since NDK r23 in favour of [only needing to link against `libunwind`].  Since this Rust release is over 1.5 years old, assume everyone is using at least 1.68 and drop the workaround from our repackaged NDK release.
[Rust 1.68 is now targeting NDK r25]: https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html#other-changes
[only needing to link against `libunwind`]: https://blog.rust-lang.org/2023/01/09/android-ndk-update-r25.html
=> CI: Remove `libgcc.a` linker workaround from repackaged NDK

xbuild/src/cargo/mod.rs, xbuild/src/lib.rs
=> Add `--no-default-features` cargo argument

xbuild/src/devices/adb.rs
We have some phones, including the Vivo X90 Pro which return an empty string for `logcat -t 1`, resulting in an `unwrap()` crash before starting logging.  There doesn't appear to be any reason to check the time of the latest **random** (not even `--uid`-scoped) message in `logcat` as we can just read the current date and time as well.  We haven't started the app yet either way, and this timestamp is inevitably already going to be later than the most recent message.
Also remove some unnecessary shell escaping (which should have been done by `shlex` otherwise) by calling `adb logcat` rather than `adb shell logcat`.
=> adb: Use current date/time instead of last `logcat` line for timestamp
